### ISSUE TITLE
GDB fork that fixes mdebug support

### ISSUE THREAD

**Issue by zZeck** [command-tab/awesome-n64-development#48]
I don't have a build bot or anything, but I [fixed the mdebug problems in GDB](https://github.com/zZeck/binutils-gdb/tree/mdebugfix) (it used to cause segfaults). This is useful for projects built with the IDO compiler since it uses that symbol format.

It may also be worth noting that since [November](https://ares-emu.net/news/ares-v134-released), Ares has had a GDB stub for use with its n64 core.

I have used Ares with my patched GDB to have a nice experience debugging SM64.

**Comment by command-tab** [comment]
Nice work! I don't think there's anything specific to change in this repo's list as a result, but it's excellent to have it out there and searchable for those who run into those issues.

It might be worth asking the Ares maintainers about potentially writing up something about your patch in a README for their project, since getting a functioning debugger can be difficult and it is incredibly useful once it works.

Thanks!
